---
- name: Add apt repositories
  apt_repository:
    repo: "{{ item }}"
    state: present
    update_cache: no
  loop:
    - "ppa:wireguard/wireguard"
  ignore_errors: yes
- name: Upgrade all packages to the latest version
  apt:
    update_cache: yes
    upgrade: dist
  ignore_errors: yes
- name: Install kernel and headers
  apt:
    name: "{{ packages }}"
  vars:
    packages:
    - "linux-image-{{ kernel_kind }}"
    - "linux-headers-{{ kernel_kind }}"
  when: handle_kernel_install
- name: Install packages
  apt:
    name: "{{ packages }}"
  vars:
    packages:
    - git
    - tmux
    - mc
    - pwgen
    - wireguard
    - ufw
    - dropbear-initramfs
    - vnstat
    - etckeeper
    - fail2ban
    - unzip
- name: Remove obsolete packages
  apt:
    autoclean: yes
    autoremove: yes
- name: create rclone directory
  file:
    name: /opt/rclone
    state: directory
    owner: root
    group: root
- name: install rclone
  unarchive:
    dest: /opt/rclone
    remote_src: yes
    src: "{{ url_rclone }}"
    extra_opts: ["-j"]
- name: set rclone permissions
  file:
    path: /opt/rclone/rclone
    owner: root
    group: root
    mode: 0755
- name: create rclone symlink
  file:
    src: /opt/rclone/rclone
    dest: /usr/local/bin/rclone
    state: link
    owner: root
    group: root
    mode: 0755
