---
- name: Deploy systemd-journald configuration
  template:
    src: templates/etc/systemd/journald.conf
    dest: /etc/systemd/journald.conf
    owner: root
    mode: 0644
  notify:
   - restart journald
