---
- name: Create group 'ssh-users'
  group:
    name: ssh-users
    state: present
- name: "Create user"
  user:
    name: "{{ ssh_username }}"
    append: yes
    groups: sudo,ssh-users
    state: present
    shell: /bin/bash
  register: usercreate
- name: "Force user to change password"
  shell: "passwd -d {{ ssh_username }} && chage -d 0 {{ ssh_username }}"
  when: usercreate.changed
- name: Set authorized key taken from file
  authorized_key:
    user: "{{ ssh_username }}"
    state: present
    key: "{{ ssh_pubkey }}"
- name: Deploy sshd configuration
  template:
    src: templates/etc/ssh/sshd_config.j2
    dest: /etc/ssh/sshd_config
    owner: root
    mode: 0644
  notify:
   - restart sshd
# We need to force sshd to restart to avoid having firewall issues later
- meta: flush_handlers