---
- name: restart sshd
  service:
    name: sshd
    enabled: yes
    state: restarted
- name: restart journald
  service:
    name: systemd-journald
    state: restarted
- name: reload sysctl
  shell: sysctl --system
