---
- name: restart sshd
  systemd:
    name: sshd
    enabled: yes
    state: restarted
- name: restart journald
  systemd:
    name: systemd-journald
    state: restarted
- name: reload sysctl
  shell: sysctl --system
- name: restart fail2ban
  systemd:
    state: restarted
    enabled: yes
    name: fail2ban
